### ISSUE TITLE
Had the code been stolen 🤔 ?

### ISSUE THREAD

**Issue by golxzn** [Gab-ani/Godot_Univerasal-Controller-tutorial-2#1]
Hi! Your videos are really great and I'd like to take a closer look to the codebase. The link under the video moves here and... Where's the code?

**Comment by Gab-ani** [comment]
Ajaja, no, it was lost, I am a pepega who originally planned to spam repo per episode, but later changed just to branch per episode. I made a mistake stitching file directories and deleted 2nd proj before creating a branch for it(. Currently, the only way to restore it is to downgrade from 3d state of the project, deleting everything but Run, Sprint and Idle states. Nothing critical was changed tho, sincerely, the 2nd episode is just a theory drop with code examples used as a background for video, you can seek the structure of discussed parts in 3d branch in main repo, nothing was changed, only added.

**Comment by golxzn** [comment]
Okay, thank you for your answer and really hard youtube work!
